---
abstract: 'install a L<Devel::StackTrace::AsHTML> error screen for your CGI app'
author:
  - 'Rafael Kitover <rkitover@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Carp-StackTrace
no_index: {}
requires:
  CGI::Carp: 0
  Devel::StackTrace::AsHTML: 0
  Devel::StackTrace::WithLexicals: 0
  HTML::Entities: 0
  perl: 5.008001
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=CGI-Carp-StackTrace
  homepage: http://metacpan.org/release/CGI-Carp-StackTrace
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rkitover/cgi-carp-stacktrace.git
version: 0.01
x_authority: cpan:RKITOVER
